const restaurants = (req, res) => {
  res.send([
    {
      id: 1,
      name: "Dark Brown",
      cloudinaryImageId: "mzdetw2s1ihmpiegkhyl",
      locality: "Shopping Centre Market",
      areaName: "Sector 16",
      costForTwo: "₹250 for two",
      cuisines: [
        "Italian-American",
        "Continental",
        "Burgers",
        "Pizzas",
        "Pastas",
        "Chinese",
        "Beverages",
        "Salads",
        "Asian",
        "Healthy Food",
        "Fast Food",
      ],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
    },

    {
      id: 2,
      name: "Star Crust",
      cloudinaryImageId: "hgte5u6o5gvvluewdwet",
      locality: "Sector 10",
      areaName: "Sector 10",
      costForTwo: "₹250 for two",
      cuisines: [
        "Pizzas",
        "Chinese",
        "Fast Food",
        "Burgers",
        "Italian-American",
        "Beverages",
        "Italian",
        "Tandoor",
      ],
      avgRating: 4,
      veg: true,
      avgRatingString: "4.0",
      totalRatingsString: "10K+",
      isOpen: true,
    },
    {
      id: 3,
      name: "KFC",
      cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
      locality: "Eldeco Station 1 Mall",
      areaName: "Sector 12",
      costForTwo: "₹450 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "1K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
    },
    {
      id: 4,
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Eldeco Station 1 Mall",
      areaName: "Sector 12",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4,
      avgRatingString: "4.0",
      totalRatingsString: "10K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "EVERY ITEM",
        subHeader: "@ ₹129",
      },
    },
    {
      id: 5,
      name: "Wow! Momo",
      cloudinaryImageId: "0984acc0ed7b914206dbbcb90297becc",
      locality: "Sector 15",
      areaName: "Sector 15",
      costForTwo: "₹300 for two",
      cuisines: [
        "Tibetan",
        "Healthy Food",
        "Asian",
        "Chinese",
        "Snacks",
        "Continental",
        "Desserts",
        "Beverages",
      ],
      avgRating: 3.8,
      avgRatingString: "3.8",
      totalRatingsString: "1K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
      },
    },
    {
      id: 6,
      name: "Chaayos Chai+Snacks=Relax",
      cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
      locality: "Shopping Centre Market",
      areaName: "Sector 15",
      costForTwo: "₹250 for two",
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
      },
    },
    {
      id: 7,
      name: "Faasos - Wraps & Rolls",
      cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
      locality: "Nehru Ground",
      areaName: "New Industrial Township",
      costForTwo: "₹200 for two",
      cuisines: [
        "Kebabs",
        "Fast Food",
        "Snacks",
        "North Indian",
        "American",
        "Healthy Food",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4,
      avgRatingString: "4.0",
      totalRatingsString: "1K+",
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
      },
    },

    {
      id: 8,
      name: "Nirula's",
      cloudinaryImageId: "whgmbmdif5udm6patgib",
      locality: "Sector-15 Market",
      areaName: "Sector 15",
      costForTwo: "₹500 for two",
      cuisines: [
        "Pizzas",
        "Burgers",
        "Ice Cream",
        "North Indian",
        "Fast Food",
        "Asian",
        "Pastas",
        "Desserts",
        "Beverages",
        "Snacks",
      ],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
      isOpen: true,
    },

    {
      id: 9,
      name: "House of Chow",
      cloudinaryImageId: "6e97ac8f5c89213610309ef1940afa05",
      locality: "Town Park",
      areaName: "Sector 12",
      costForTwo: "₹300 for two",
      cuisines: ["Pan-Asian", "Chinese", "Thai", "Oriental"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "5K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
    },
    {
      id: 10,
      name: "Oven Story Pizza - Standout Toppings",
      cloudinaryImageId: "f986df6f1a1fcf2ff24d2eaf44d570a7",
      locality: "Nehru Ground",
      areaName: "New Industrial Township",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRating: 3.7,
      avgRatingString: "3.7",
      totalRatingsString: "1K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹1099",
        discountTag: "FLAT DEAL",
      },
    },
    {
      id: 11,
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "PM Metropolitan Mall",
      areaName: "New Industrial Township",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 3.6,
      avgRatingString: "3.6",
      totalRatingsString: "1K+",
      isOpen: true,
    },
    {
      id: 12,
      name: "McDonald's",
      cloudinaryImageId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
      locality: "Crown Plaza Mall",
      areaName: "Sector 15",
      costForTwo: "₹400 for two",
      cuisines: ["American"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
      isOpen: true,
    },
    {
      id: 13,
      name: "La Pino'z Pizza",
      cloudinaryImageId: "mzb8tq7ccskyvadm9mt2",
      locality: "Shopping Centre Market",
      areaName: "Sector 15",
      costForTwo: "₹250 for two",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRating: 3.8,
      avgRatingString: "3.8",
      totalRatingsString: "10K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹399",
        discountTag: "FLAT DEAL",
      },
    },
    {
      id: 14,
      name: "Sweet Truth - Cake and Desserts",
      cloudinaryImageId: "4a3b48488e3aa9bda13efd8cfcd95284",
      locality: "Rani Bhawan",
      areaName: "New Industrial Township",
      costForTwo: "₹450 for two",
      cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
      avgRating: 4,
      avgRatingString: "4.0",
      totalRatingsString: "100+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
      },
    },
    {
      id: 15,
      name: "Barbeque Nation",
      cloudinaryImageId: "fmoykif0fxrlc2l8tdos",
      locality: "Sector 20",
      areaName: "Sector 20",
      costForTwo: "₹600 for two",
      cuisines: [
        "North Indian",
        "Barbecue",
        "Biryani",
        "Kebabs",
        "Mughlai",
        "Desserts",
      ],
      avgRating: 3.7,
      avgRatingString: "3.7",
      totalRatingsString: "500+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
      },
    },
    {
      id: 16,
      name: "Chai Point",
      cloudinaryImageId: "znobbbace3njt7oxau2f",
      locality: "Adb Pwd Colony",
      areaName: "Sector 16",
      costForTwo: "₹150 for two",
      cuisines: [
        "Bakery",
        "Beverages",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "South Indian",
        "Punjabi",
        "Chaat",
        "Indian",
        "American",
        "North Indian",
        "Fast Food",
        "Desserts",
        "Cafe",
        "Healthy Food",
        "Home Food",
      ],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
      isOpen: true,
      attributes: {
        description: "",
        fontColor: "#7E808C",
        iconId: "guiltfree/GF_Logo_android_3x",
        shortDescription: "options available",
      },
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
      },
    },
    {
      id: 17,
      name: "ABC Biryani Wala",
      cloudinaryImageId: "pdtdjeece6pgbmjq5mft",
      locality: "Bk Chowk",
      areaName: "New Industrial Township",
      costForTwo: "₹200 for two",
      cuisines: ["Biryani"],
      avgRating: 3.8,
      avgRatingString: "3.8",
      totalRatingsString: "10K+",
      isOpen: true,
    },
    {
      id: 18,
      name: "Hunger Cure (Pure Veg)",
      cloudinaryImageId: "vgekitzjwk1r63uxneov",
      locality: "Sector-79",
      areaName: "Omaxe World Street",
      costForTwo: "₹300 for two",
      cuisines: [
        "North Indian",
        "Chinese",
        "Burgers",
        "Pastas",
        "Pizzas",
        "Fast Food",
        "Snacks",
        "Beverages",
        "Continental",
        "Indian",
        "Italian",
        "American",
      ],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹499",
        discountTag: "FLAT DEAL",
      },
    },
    {
      id: 19,
      name: "Hunger Cure",
      cloudinaryImageId: "ob7ojusjqhjfe7lt9dcx",
      locality: "Friends Colony",
      areaName: "Sector 14",
      costForTwo: "₹300 for two",
      cuisines: [
        "Chinese",
        "Continental",
        "Burgers",
        "Pastas",
        "Pizzas",
        "Beverages",
        "Italian",
        "American",
        "Snacks",
        "Fast Food",
      ],
      avgRating: 4.2,
      veg: true,
      avgRatingString: "4.2",
      totalRatingsString: "5K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
      },
    },
    {
      id: 20,
      name: "Behrouz Biryani",
      cloudinaryImageId: "89fccaa76f2f760e2742b9e53d32bb69",
      locality: "Nehru Ground",
      areaName: "New Industrial Township",
      costForTwo: "₹500 for two",
      cuisines: [
        "Biryani",
        "Mughlai",
        "North Indian",
        "Lucknowi",
        "Hyderabadi",
        "Kebabs",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      isOpen: true,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹399",
        discountTag: "FLAT DEAL",
      },
    },
  ]);
};

module.exports = {
  restaurants,
};
